"""Add legal notice system

Revision ID: 31a63fc03e0b
Revises: a1b2c3d4e5f6
Create Date: 2025-12-18 20:07:56.404720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a63fc03e0b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_contract_id'), table_name='document_versions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_versions_contract_id'), 'document_versions', ['contract_id'], unique=False)
    # ### end Alembic commands ###
