"""Add title evidence_guide damage_summary to legal_notice_sessions

Revision ID: a5e82de87444
Revises: 7dd376ca9cf8
Create Date: 2025-12-19 07:54:08.574384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e82de87444'
down_revision: Union[str, Sequence[str], None] = '7dd376ca9cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_notice_sessions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('legal_notice_sessions', sa.Column('evidence_guide', sa.Text(), nullable=True))
    op.add_column('legal_notice_sessions', sa.Column('damage_summary', sa.Text(), nullable=True))
    op.alter_column('legal_notice_sessions', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('legal_notice_sessions_contract_id_fkey', 'legal_notice_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'legal_notice_sessions', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'legal_notice_sessions', type_='foreignkey')
    op.create_foreign_key('legal_notice_sessions_contract_id_fkey', 'legal_notice_sessions', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.alter_column('legal_notice_sessions', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('legal_notice_sessions', 'damage_summary')
    op.drop_column('legal_notice_sessions', 'evidence_guide')
    op.drop_column('legal_notice_sessions', 'title')
    # ### end Alembic commands ###
