"""Add extracted_text column to contracts

Revision ID: c8ad02008ca9
Revises: 3ca29ea5fdf3
Create Date: 2025-12-03 07:17:16.109996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ad02008ca9'
down_revision: Union[str, Sequence[str], None] = '3ca29ea5fdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'extracted_text')
    # ### end Alembic commands ###
